### ISSUE TITLE
Can't we use it in blender 3.xx versions???

### ISSUE THREAD

**Issue by inderxkang** [RealIndrit/blender-openctm#3]
As you defined in readme the script is for blender 4.2 or up 
Is it possible to import these type of mesh in versions 3.xx because the 4.2 needs higher opengl version 😞

**Comment by RealIndrit** [comment]
I can look into it tonight. But short summary why it's 4.2. It's the only version I have tested. So the plugin is tagged as 4.2 and up only to avoid it crashing blender or itself. (I suspect that importing mesh data might differ tiny bit between 3.xx and 4.xxx) But if I add support it would be only tested against the latest 3.x LTS release.

**Comment by inderxkang** [comment]
and does it supports windows x64 only 
i tried on blender 4.2 running on ubuntu jammy x64 and got an error
"openctm_ctm: This platform (linux-x64) isn't one of (windows-x64)"

**Comment by inderxkang** [comment]
ok

**Comment by RealIndrit** [comment]
Blender 3.6 support is added (Not fully tested)
